name: Cross - Build and Test

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest,macos-latest, macos-15-large]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # 更新到 v4

      - name: Make script executable
        run: chmod +x ./build_boost.sh  # 添加执行权限

      - name: Run build boost script
        run: ./build_boost.sh # 确保脚本可执行

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4  # 更新到 v4
        with:
          name: boost-${{ matrix.os }}
          path: |
            cdeps_boost_1_88.zip
          retention-days: 1

      - name: Fail if execution failed
        if: env.exit_code != '0'
        run: exit ${{ env.exit_code }}
